### PR TITLE
More tests + n-grams

### PR DESCRIPTION
**Pull request by Skizzk**
Adding more tests
Introduction of n-grams parsing

### CODE REVIEW

**Comment by jemminger** [comment]
Wow, very nice!  One thing I noticed: The Gemfile.lock is [showing v1.2.0](https://github.com/7compass/sentimental/pull/11/files#diff-e79a60dc6b85309ae70a6ea8261eaf95R4) while the gemspec says [v1.2.1](https://github.com/7compass/sentimental/pull/11/files#diff-dd037ecacbe48569c74bdb51cd6b8262R3)

Was this intentional?

**Comment by Skizzk** [comment]
Nope an error on my side. Fixing it right now.

**Comment by jemminger** [comment]
@Skizzk You've been pretty active with this gem, do you want commit rights?

**Comment by Skizzk** [comment]
Oh. That would be nice :) Thank you :) (And thanks for the initial work btw)

**Comment by jemminger** [comment]
Ok, you should have write permissions now.  I can give you push rights to rubygems.org too, just send me your email to jemminger(a)gmail-com

**Pull request merged**
